'use client';

import React, { useEffect, useState, use } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { AppShell } from '../../../components/layout/AppShell';
import { orchestratorService } from '../../../lib/services/orchestrator';
import { Remediation, Finding } from '../../../lib/types';
import { PatchViewer } from '../../../components/code/PatchViewer';
import { StatusBadge } from '../../../components/ui/StatusBadge';
import { ArrowLeft, Play, FileDiff } from 'lucide-react';

export default function RemediationPage({ params }: { params: Promise<{ remediationId: string }> }) {
  const resolvedParams = use(params);
  const router = useRouter();
  const [remediation, setRemediation] = useState<Remediation | null>(null);
  const [finding, setFinding] = useState<Finding | null>(null);

  useEffect(() => {
    orchestratorService.getRemediationById(resolvedParams.remediationId).then(async (rem) => {
      if (rem) {
        setRemediation(rem);
        const f = await orchestratorService.getFindingById(rem.findingId);
        if (f) setFinding(f);
      }
    });
  }, [resolvedParams.remediationId]);

  const handleValidate = () => {
    router.push('/validation/VAL-SEC-001');
  };

  if (!remediation || !finding) {
    return (
      <AppShell>
        <div className="py-12 text-center text-gray-400 font-mono text-xs">
          Loading candidate remediation artifact {resolvedParams.remediationId}...
        </div>
      </AppShell>
    );
  }

  return (
    <AppShell>
      <div className="space-y-4 sm:space-y-5 max-w-full">
        {/* Navigation Breadcrumb */}
        <Link
          href={`/findings/${finding.id}`}
          className="inline-flex items-center gap-1.5 text-xs text-gray-400 hover:text-gray-200 transition-colors font-mono"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to Finding {finding.id}</span>
        </Link>

        {/* Remediation Header Card */}
        <div className="bg-[#161b22] border border-[#30363d] rounded p-4 sm:p-5 flex flex-col md:flex-row md:items-center justify-between gap-4 min-w-0">
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2 font-mono text-xs">
              <span className="font-bold text-gray-100">{remediation.id}</span>
              <span className="text-gray-500">•</span>
              <span className="text-gray-400 truncate">Target: {finding.id}</span>
              <StatusBadge status={remediation.status} />
            </div>

            <h1 className="text-base sm:text-lg font-bold text-gray-100 font-sans mt-1.5">{remediation.strategy}</h1>
            <p className="text-xs text-gray-400 font-mono mt-0.5 truncate">
              Generated by: <span className="text-gray-200">{remediation.model}</span> • Confidence:{' '}
              <span className="text-emerald-400 font-semibold">{remediation.confidence}%</span>
            </p>
          </div>

          <button
            onClick={handleValidate}
            className="flex items-center justify-center gap-2 px-4 py-2 rounded bg-[#21262d] hover:bg-[#30363d] text-gray-100 border border-[#30363d] text-xs font-semibold transition-colors shrink-0 self-start md:self-auto"
          >
            <Play className="w-3.5 h-3.5 fill-current" />
            <span>Validate Fix in Pipeline</span>
          </button>
        </div>

        {/* Patch Viewer Unified Diff */}
        <div className="space-y-2">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <FileDiff className="w-4 h-4 text-gray-400 shrink-0" />
              <h2 className="text-sm font-semibold text-gray-200">Generated Candidate Patch Diff</h2>
            </div>
            <span className="text-xs font-mono text-gray-400">
              {remediation.filesChanged.length} files modified
            </span>
          </div>

          <PatchViewer patch={remediation.patch} filesChanged={remediation.filesChanged} />
        </div>

        {/* Rationale & Risk Assessment Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs font-mono">
          {/* Root Cause Analysis */}
          <div className="bg-[#161b22] border border-[#30363d] rounded p-3.5 space-y-1.5 min-w-0">
            <span className="text-gray-500 text-[10px] block uppercase font-medium">1. ROOT CAUSE ANALYSIS</span>
            <p className="text-gray-200 leading-relaxed font-sans">{remediation.rootCause}</p>
          </div>

          {/* Regression Risks */}
          <div className="bg-[#161b22] border border-[#30363d] rounded p-3.5 space-y-1.5 min-w-0">
            <span className="text-gray-500 text-[10px] block uppercase font-medium">2. REGRESSION RISK ASSESSMENT</span>
            <div className="flex flex-wrap items-center gap-2">
              <span className="px-2 py-0.5 rounded bg-emerald-500/10 border border-emerald-800/40 text-emerald-400 text-[10px] font-bold">
                {remediation.risk} RISK
              </span>
              <span className="text-gray-400 font-sans">Low probability of interface side effects.</span>
            </div>
          </div>

          {/* Key Assumptions */}
          <div className="bg-[#161b22] border border-[#30363d] rounded p-3.5 space-y-1.5 md:col-span-2 min-w-0">
            <span className="text-gray-500 text-[10px] block uppercase font-medium">3. SYSTEM ASSUMPTIONS & VERIFICATIONS</span>
            <ul className="list-disc list-inside text-gray-300 space-y-1 font-sans">
              {remediation.assumptions.map((ass, i) => (
                <li key={i}>{ass}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
